#xtx
CorridorDists = {        
                "Reception":1,                          
                "Corridor 1a":10,"Corridor 1b":3,
                "Corridor 2a":8,"Corridor 2b":1, "Corridor 2c":1, "Corridor 2x":1,
                "Corridor 3":2,
                "Corridor 4a":10,"Corridor 4b":2,"Corridor 4x":1,
                "Atrium a":11,"Atrium b":2,
                "Corridor 5":4,"Corridor 5xa":1,"Corridor 5xb":1,
                "Corridor 6a":2.5,"Corridor 6b":2.5,"Corridor 6c":3,"Corridor 6d":3,"Corridor 6e":3,
                "Corridor 7":2,"Corridor 7x":2,
                "Corridor 8a":6,"Corridor 8b":2,
                "Corridor 9a":2,"Corridor 9b":3,"Corridor 9c":3,"Corridor 9x":1,
                "Corridor 10a":2,"Corridor 10b":4,
                "Corridor 11a":5,"Corridor 11b":5,
                "Corridor 12a":5, "Corridor 12b":5,
                "Corridor 13a":3, "Corridor 13b":2,
                "Corridor 14a":5, "Corridor 14x":1,"Corridor 14b":5,
                "Corridor 15a":3, "Corridor 15b":4,"Corridor 15c":3,
                "Corridor 16":4,
                "Corridor 17a":4,"Corridor 17b":3,"Corridor 17c":3,"Corridor 17x":1,
                "Corridor 18a":5,"Corridor 18b":5,
                "Corridor 19a":5,"Corridor 19b":5,
                "Corridor 20":6,
                "Corridor 21":5,
                "Corridor 22":4,
                "Corridor 23a":4,
                "Corridor 23b":1,
                "Corridor 24":6,
                "Corridor 25":3,
                "Corridor 25x":1,
                "Corridor GSLi":1,
                "Corridor GSR":1,
                "Corridor GSL":1,
                "Corridor GSH":1,
                "Corridor GSC":1,
                "Corridor GSB":1,
                "Corridor GSE":1,
                "Corridor GSSD":1,
                "Corridor GSDS":1,
                "Corridor GSLtn":1,
                "Corridor 26x-Out2b":3,
                "Corridor Out2a-Out2b":3,
                "Corridor Out2b-Out3":5,
                "Corridor 1x-Out3":2,
                "Corridor Out3-Out4":10,
                "Corridor 2x-Out4":2,
                "Corridor Out4-Out5":3,
                "Corridor 4x-Out5":13,
                "Corridor 4x-5xa":2,
                "Corridor 5xa-Out6":4,
                "Corridor 10x-Out6":5,
                "Corridor 10x-13x":6,
                "Corridor 13x-SPb":15,
                "Corridor SPa-SPb":2,
                "Sports Pavillion":1,
                "Corridor SPb-Out1b":3,
                "Corridor M-Out1b":2,
                "Corridor 20xa-Out1b":5,
                "Corridor SHb-Out1b":3,
                "Corridor SHa-SHb":2,
                "Sports Hall":1,
                "Corridor SHa-Out7":20,
                "Corridor Out7-28xa":11,
                "Corridor 28xa-Out2a":2,
                #First Floor
                "Corridor 30a-StairsA":1,
                "Corridor 29-StairsA":1,
                "Corridor 30b-StairsA":8,
                "Corridor 30b-StairsB":1,
                "Corridor 31a-StairsB":3,
                "Corridor 31a-StairsC":3,
                "Corridor 30b-32b":7,
                "Corridor 31b-StairsC":4,
                "Corridor 31b-StairsD":2,
                "Corridor 32b-StairsD":1,
                "Corridor 32a-32b":8,
                "Corridor 32a-Stairs":2,
                "Corridor 32a-33b":4,
                "Corridor 31b-StairsK":3,
                "Corridor 31c-StairsK":1,
                "Corridor 31c-StairsE":4,
                "Corridor 33b-StairsE":5,
                "Corridor 33b-StairsF":1,
                "Corridor StairsF-StairsG":4,
                "Corridor 33a-StairsG":6,
                "Corridor 33a-StairsH":2,
                "Corridor Stairs-34":5,
                "Corridor 35-StairsI":3,
                "Corridor StairsI-StairsJ":3,
                "Corridor 36a-Stairs":1,
                "Corridor 36a-36b":5,
                "Corridor 36b-Stairs":5,
                "Corridor 36c-Stairs":3,
                #Ground-First Stair Connectors
                "Corridor Reception Ground-First":1,
                "Corridor Library Ground-First":1,
                "Corridor Language Ground-First":1,
                "Corridor History Ground-First":1,
                "Corridor Chemistry Ground-First":1,
                "Corridor Bioligy Ground-First":1,
                "Corridor Art Ground-First":1,
                "Corridor Latin Ground-First":1,
                "Corridor English Ground-First":1,
                "Corridor Staff Dining Ground-First":1,
                "Corridor Dance Studio Ground-First":1,
                #Second Floor
                "Corridor 37a-Stairs":3,
                "Corridor 37a-37b":4,
                "Corridor 37b-37c":2,
                "Corridor 37c-37d":2,
                "Corridor 37b-37e":4,
                "Corridor 37c-37f":3,
                "Corridor 37c-Stairs":1,
                "Corridor 37d-Stairs":5,
                "Corridor 40-Stairs":1,
                "Corridor 39-Stairs":4,
                "Corridor 37a-38a":5,
                "Corridor 38a-StairsA":2,
                "Corridor 38a-StairsB":3,
                "Corridor 38b-StairsB":2,
                            }

CorridorContent = {
    "Reception":["0Headmaster's Study","0G1","9G2","0Main Entrance"],
    "Corridor GSR":["0Ground Reception Stairs"],
    "Corridor 1a":["2G3","3G4","3G5","4G6","5G7","6G8","7G9","8G10"],
    "Corridor 1b":[],
    "Corridor 2a":["0G11","2G12","2G13","4G14","5G15","5Barry Martin Centre","7G16","8G17"],"Corridor 2b":["0Cloisters",],"Corridor 2c":[],"Corridor 2x":[],
    "Corridor GSLi":["0Ground StairsToLibrary"],
    "Corridor GSL":["0Ground StairsToLanguage"],
    "Corridor 3":[],
    "Corridor 4a":["0G25","3G24","6G23","8G18","7Barry Martin Centre"],"Corridor 4b":[],"Corridor 4x":[],
    "Atrium a":["0G42","0G43","0G44","0G45","1G46","3G57","5Ground Atrium Toilets","5G48","7G49"],"Atrium b":[],
    "Corridor 5":["3G51","5G52","7G53","8Ground History Toilets","9G54"],"Corridor 5xb":["0G50"],"Corridor 5xa":[],
    "Corridor GSH":["0Ground StairsToHistory"],
    "Corridor 6a":["9G64",],"Corridor 6b":["8G62","4G63"],"Corridor 6c":["0G61"],"Corridor 6d":["8G58",],"Corridor 6e":["GG56","3G55","0G57"],
    "Corridor GSC":["0Ground StairsToChemistry"],
    "Corridor GSB":["0Ground StairsToBioligy"],
    "Corridor 7":[],"Corridor 7x":[],
    "Corridor 8a":[],"Corridor 8b":[],
    "Corridor 9a":[],"Corridor 9b":["2G72","2G70","4G71","4G69","9G68","3Ground StairsToArt",],"Corridor 9c":["0G67"],"Corridor 9x":[],
    "Corridor 10a":[],"Corridor 10b":["9G66","9G65"],
    "Corridor 11a":["8G32","6G33","3G41","1G34"],"Corridor 11b":["0G30","0G31"],#check g34 corridor approach
    "Corridor 12a":["2Ground Disabled Toilets Cloisters","5Ground Toilets Cloisters"], "Corridor 12b":["4G29","5G28","8G26","9G27"],
    "Corridor GSLtn":["0Ground StairsToLatin",],
    "Corridor 13a":[], "Corridor 13b":[],
    "Corridor 14a":["1Medical Room","3G91A","5G91B"], "Corridor 14x":["0Main School Queue"],"Corridor 14b":["2G38","2G39","4G36","4G37","4G40","7G35"],
    "Corridor 15a":["0G79"], "Corridor 15b":[],"Corridor 15c":[],
    "Corridor 16":["3Toilets,Ground,DesEng","4G75","7G74a","7G74","9G73","5G78"],
    "Corridor GSE":["0Ground StairsToEnglish","1G76","1G77",],
    "Corridor 17a":["0Ground Lift HammondTheatre","5Hammond Theatre","9Ground Disabled Toilets HammondTheatre"],"Corridor 17b":["0Ground Staff Toilets HammondTheatre","3G81","9Changing Room,Ground,North Gym"],"Corridor 17c":[],"Corridor 17x":[],
    "Corridor 18a":[],"Corridor 18b":[],
    "Corridor 19a":[],"Corridor 19b":[],
    "Corridor 20":["0G86","0Ground Toilets HammondTheatre","G85"],
    "Corridor 21":["0G89","3G88","4G87","5Ground Lift Dance Studio"],
    "Corridor GSDS":["0Ground StairsToDanceStudio",],
    "Corridor 22":["9Lower School Queue"],
    "Corridor 23":["4Dining Hall"],
    "Corridor GSSD":["0Ground StairsToStaffDining"],
    "Corridor 24":["5Practise Rooms","0P11","7P10","9Ground Staff Toilets Garrik","8P9"],
    "Corridor 25":["7P1","4P2","4P8","2P7","2P3","0P4","0P5","0P6"],
    "Corridor 25x":["0Garrik"],
    "Corridor 26x-Out2b":[],
    "Corridor Out2a-Out2b":[],
    "Corridor Out2b-Out3":[],
    "Corridor 1x-Out3":[],
    "Corridor Out3-Out4":[],
    "Corridor 2x-Out4":[],
    "Corridor Out4-Out5":[],
    "Corridor 4x-Out5":[],
    "Corridor 4x-5xa":[],
    "Corridor 5xa-Out6":[],
    "Corridor 10x-Out6":[],
    "Corridor 10x-13x":[],
    "Corridor 13x-SPb":[],
    "Corridor SPa-SPb":[],
    "Sports Pavillion":["0Sports Pavillion"],
    "Corridor SPb-Out1b":[],
    "Corridor M-Out1b":["0M Block","0M1","0M2","0M3"],
    "Corridor 20xa-Out1b":[],
    "Corridor SHb-Out1b":[],
    "Corridor SHa-SHb":[],
    "Sports Hall":["0Sports Hall"],
    "Corridor SHa-Out7":[],
    "Corridor Out7-28xa":[],
    "Corridor 28xa-Out2a":[],
    #First floor
    "Corridor 30a-StairsA":["0F1","0F2","0First Staff Toilets MainHall Balcony","9First StairsToRS"],
    "Corridor 29-StairsA":["1F3","1First Reception Stairs"],
    "Corridor 30b-StairsA":["2Main Hall Balcony","2F4","3F5","5F6","5F9","7F11","8F12","9F13"],
    "Corridor 30b-StairsB":[],
    "Corridor 31a-StairsB":["0F35","9F36"],
    "Corridor 31a-StairsC":["0F37","4F38"],
    "Corridor 30b-32b":["1F14","2F10","3F15","5F16","5F17","7F19","8F20","9F21","5F18"],
    "Corridor 31b-StairsC":["0F39","3First Toilets Atrium","4F40","8F41"],
    "Corridor 31b-StairsD":[],
    "Corridor 32b-StairsD":["9First StairsToLanguage"],
    "Corridor 32a-32b":["9F22","7F23","4F24","1F25","0F26"],
    "Corridor 32a-Stairs":["0F33","0F34","0Exams Office","1F31","3F30","6F29","6F28","6F27","0First StairsToLatin"],
    "Corridor 32a-33b":["7F59","7F56"],
    "Corridor 31b-StairsK":["9F43","9F42","9First StairsToHistory"],
    "Corridor 31c-StairsK":["0F44"],
    "Corridor 31c-StairsE":["9F45","9F46","5F47","5F49","4F51","3F52","2F50","0First StairsToChemistry"],
    "Corridor 33b-StairsE":["8F53","6F55","5F54","3F57"],
    "Corridor 33b-StairsF":["9F58","0First StairsToBioligy"],
    "Corridor StairsF-StairsG":["0First StairsToArt","2F63","4F61","5F62","7F60"],
    "Corridor 33a-StairsG":["0F72","0F71","2F70","3F69","3F68","5F67","5F66","8F65","8F64"],
    "Corridor 33a-StairsH":["0F73","0First StairsToEnglish","0F74"],
    "Corridor Stairs-34":[],#xtx need to sort out nav data for pavillion and sports hall but consider not connected for now
    "Corridor 35-StairsI":[],
    "Corridor StairsI-StairsJ":[],
    "Corridor 36a-Stairs":["0F80","0First StairsToDanceStudio"],
    "Corridor 36a-36b":["0F79","0F78","4F77","5F76","7First Toilets HammondTheatre","9F75"],
    "Corridor 36b-Stairs":["0First StairsToStaffDining"],
    "Corridor 36c-Stairs":["8F81","4Staff Dining"],
    #Ground-First Stair Connectors
    "Corridor Reception Ground-First":[],
    "Corridor Library Ground-First":[],
    "Corridor Language Ground-First":[],
    "Corridor History Ground-First":[],
    "Corridor Chemistry Ground-First":[],
    "Corridor Bioligy Ground-First":[],
    "Corridor Art Ground-First":[],
    "Corridor Latin Ground-First":[],
    "Corridor English Ground-First":[],
    "Corridor Staff Dining Ground-First":[],
    "Corridor Dance Studio Ground-First":[],
    #Second Floor
    "Corridor 37a-Stairs":["0Second StairsToLatin","0S32","0S31","3S30","9S29","9S28"],
    "Corridor 37a-37b":["2S27","8S26"],
    "Corridor 37b-37c":["1S19","6S16"],
    "Corridor 37c-37d":2,
    "Corridor 37b-37e":4,
    "Corridor 37c-37f":3,
    "Corridor 37c-Stairs":1,
    "Corridor 37d-Stairs":5,
    "Corridor 40-Stairs":1,
    "Corridor 39-Stairs":4,
    "Corridor 37a-38a":5,
    "Corridor 38a-StairsA":2,
    "Corridor 38a-StairsB":3,
    "Corridor 38b-StairsB":2,
    }

# StairsGround = ["0Reception Stairs,Ground","0StairsToLibrary,Ground","0StairsToLanguage,Ground","3StairsToHistory,Ground",
#           "1StairsToBioligy,Ground","0StairsToChemistry,Ground","0GStairsToArt,Ground","3StairsToLatin,Ground",
#           "0StairsToEnglish,Ground","5StairsToDanceStudio,Ground","9StairsToStaffDining,Ground"]


#Note i ignore the stair floor connecting corridors as you would never start/end in these cuz thers no rooms in any of them
CorridorFloorMapper = {
    "Ground Floor":[                
        "Reception",                          
        "Corridor 1a","Corridor 1b",
        "Corridor 2a","Corridor 2b", "Corridor 2c", "Corridor 2x",
        "Corridor 3",
        "Corridor 4a","Corridor 4b","Corridor 4x",
        "Atrium a","Atrium b",
        "Corridor 5","Corridor 5xa","Corridor 5xb",
        "Corridor 6a","Corridor 6b","Corridor 6c","Corridor 6d","Corridor 6e",
        "Corridor 7","Corridor 7x",
        "Corridor 8a","Corridor 8b",
        "Corridor 9a","Corridor 9b","Corridor 9c","Corridor 9x",
        "Corridor 10a","Corridor 10b",
        "Corridor 11a","Corridor 11b",
        "Corridor 12a", "Corridor 12b",
        "Corridor 13a", "Corridor 13b",
        "Corridor 14a", "Corridor 14x","Corridor 14b",
        "Corridor 15a", "Corridor 15b","Corridor 15c",
        "Corridor 16",
        "Corridor 17a","Corridor 17b","Corridor 17c","Corridor 17x",
        "Corridor 18a","Corridor 18b",
        "Corridor 19a","Corridor 19b",
        "Corridor 20",
        "Corridor 21",
        "Corridor 22",
        "Corridor 23a",
        "Corridor 23b",
        "Corridor 24",
        "Corridor 25",
        "Corridor 25x",
        "Corridor GSLi",
        "Corridor GSR",
        "Corridor GSL",
        "Corridor GSH",
        "Corridor GSC",
        "Corridor GSB",
        "Corridor GSE",
        "Corridor GSSD",
        "Corridor GSDS",
        "Corridor GSLtn",
        "Corridor 26x-Out2b",
        "Corridor Out2a-Out2b",
        "Corridor Out2b-Out3",
        "Corridor 1x-Out3",
        "Corridor Out3-Out4",
        "Corridor 2x-Out4",
        "Corridor Out4-Out5",
        "Corridor 4x-Out5",
        "Corridor 4x-5xa",
        "Corridor 5xa-Out6",
        "Corridor 10x-Out6",
        "Corridor 10x-13x",
        "Corridor 13x-SPb",
        "Corridor SPa-SPb",
        "Sports Pavillion",
        "Corridor SPb-Out1b",
        "Corridor M-Out1b",
        "Corridor 20xa-Out1b",
        "Corridor SHb-Out1b",
        "Corridor SHa-SHb",
        "Sports Hall",
        "Corridor SHa-Out7",
        "Corridor Out7-28xa",
        "Corridor 28xa-Out2a",
                ],
    "First Floor":[                
        "Corridor 30a-StairsA",
        "Corridor 29-StairsA",
        "Corridor 30b-StairsA",
        "Corridor 30b-StairsB",
        "Corridor 31a-StairsB",
        "Corridor 31a-StairsC",
        "Corridor 30b-32b",
        "Corridor 31b-StairsC",
        "Corridor 31b-StairsD",
        "Corridor 32b-StairsD",
        "Corridor 32a-32b",
        "Corridor 32a-Stairs",
        "Corridor 32a-33b",
        "Corridor 31b-StairsK",
        "Corridor 31c-StairsK",
        "Corridor 31c-StairsE",
        "Corridor 33b-StairsE",
        "Corridor 33b-StairsF",
        "Corridor StairsF-StairsG",
        "Corridor 33a-StairsG",
        "Corridor 33a-StairsH",
        "Corridor Stairs-34",
        "Corridor 35-StairsI",
        "Corridor StairsI-StairsJ",
        "Corridor 36a-Stairs",
        "Corridor 36a-36b",
        "Corridor 36b-Stairs",
        "Corridor 36c-Stairs",
                ],
    "Second Floor":[],
    "Ground-First Floor":[    
        "Corridor Reception Ground-First",
        "Corridor Library Ground-First",
        "Corridor Language Ground-First",
        "Corridor History Ground-First",
        "Corridor Chemistry Ground-First",
        "Corridor Bioligy Ground-First",
        "Corridor Art Ground-First",
        "Corridor Latin Ground-First",
        "Corridor English Ground-First",
        "Corridor Staff Dining Ground-First",
        "Corridor Dance Studio Ground-First",
        ],
    "First-Second Floor":[],
                     }


#Add connections between floors-stairs for eadh stair node
NodeConnections = {
    "Node 1":{"Node 24":"Corridor 11a", "Node 2a":"Corridor 1a", "Node 26":"Corridor 14b","Reception Stairs Ground":"Corridor GSR"},
    "Reception Stairs Ground":{"Node 1":"Corridor GSR","Node 1x":"Reception", "Reception Stairs First":"Corridor Reception Ground-First"},
    "Node 1x":{"Reception Stairs Ground":"Reception", "Node Out3":"Corridor 1x-Out3"},
    "Node 2a":{"Node 1":"Corridor 1a", "Node 3a":"Corridor 2a","Library Stairs Ground":"Corridor GSLi","Node 2x":"Corridor 2x"},
    "Node 2b":{"Library Stairs Ground":"Corridor 1b","Node 4":"Atrium a"},
    "Library Stairs Ground":{"Node 2a":"Corridor GSLi", "Node 2b":"Corridor 1b","Library Stairs First":"Corridor Library Ground-First"},
    "Node 2x":{"Node 2a":"Corridor 2x", "Node Out4":"Corridor 2x-Out4"},
    "Node 3a":{"Node 18":"Corridor 4a","Node 3b":"Corridor 2c","Node 2a":"Corridor 2a"},
    "Node 3b":{"Language Stairs Ground":"Corridor GSL", "Node 4":"Corridor 4b", "Node 3a":"Corridor 2c"},
    "Language Stairs Ground":{"Node 3b":"Corridor GSL","Node 6":"Corridor 2b","Language Stairs Ground":"Corridor Language Ground-First"},
    "Node 4":{"Node 2b":"Atrium a", "Node 3b":"Corridor 4b", "Node 5":"Atrium b"},
    "Node 4x":{"Node 4":"Corridor 4x", "Node Out5":"Corridor 4x-Out5", "Node 5xa":"Corridor 4x-5xa"},
    "Node 5":{"Node 4":"Atrium b", "Node 6":"Corridor 3","History Stairs Ground":"Corridor GSH"},
    "History Stairs Ground":{"Node 5":"Corridor GSH","Node 5xb":"Corridor 5xa", "History Stairs First":"Corridor History Ground-First"},
    "Node 5xa":{"Node 5xb":"Corridor 5xb", "Node 4x":"Corridor 4x-5xa", "Node Out6":"Corridor 5xa-Out6"},    
    "Node 5xb":{"History Stairs Ground":"Corridor 5xa","Node 5xa":"Corridor 5xb","Node 8":"Corridor 5"},
    "Node 6":{"Language Stairs Ground":"Corridor 2b", "Node 5":"Corridor 3", "Node 7":"Corridor 8b"},
    "Node 7":{"Node 6":"Corridor 8b", "Node 10":"Corridor 7", "Node 16":"Corridor 8a"},
    "Node 8":{"Node 5xb":"Corridor 5", "Node 9":"Corridor 6e"},
    "Node 9":{"Node 8":"Corridor 6e", "Chemistry Stairs Ground":"Corridor 6d"},
    "Node 10":{"Node 11":"Corridor 6c", "Node 7":"Corridor 7", "Chemistry Stairs Ground":"Corridor GSC"},
    "Chemistry Stairs Ground":{"Node 10":"Corridor GSC", "Node 9":"Corridor 6d", "Chemistry Stairs First":"Corridor Chemistry Ground-First"},
    "Node 10x":{"Node 10":"Corridor 7x", "Node Out6":"Corridor 10x-Out6", "Node 13x":"Corridor 10x-13x"},
    "Node 11":{"Node 10":"Corridor 6b", "Node 12":"Corridor 6b",},
    "Node 12":{"Node 11":"Corridor 6b", "Node 16":"Corridor 10b", "Bioligy Stairs Ground":"Corridor 6a"},
    "Node 13":{"Node 14":"Corridor 9c", "Bioligy Stairs Ground":"Corridor GSB"},
    "Bioligy Stairs Ground":{"Node 13":"Corridor GSB", "Node 12":"Corridor 6a", "Bioligy Stairs First":"Corridor Bioligy Ground-First"},
    "Node 13x":{"Node 13":"Corridor 9x", "Node 10x":"Corridor 10x-13x", "Node SPb":"Corridor 13x-SPb"},
    "Node 14":{"Node 13":"Corridor 9c", "Node 17":"Corridor 13b", "Art Stairs Ground":"Corridor 9b"},
    "Node 15":{"Art Stairs Ground":"Corridor 9a", "Node 20":"Corridor 15a", "Art Stairs Ground":"Corridor 9a"},
    "Art Stairs Ground":{"Node 15":"Corridor 9a", "Node 14":"Corridor 9b", "Art Stairs First":"Corridor Art Ground-First"},
    "Node 16":{"Node 12":"Corridor 10b", "Node 7":"Corridor 8a", "Node 18":"Corridor 10a"},
    "Node 17":{"Node 14":"Corridor 13b", "Node 19":"Corridor 13a", "Node 20x":"Corridor 15b"},
    "Node 18":{"Node 16":"Corridor 10a", "Node 3a":"Corridor 4a", "Node 24":"Corridor 11b", "Latin Stairs Ground":"Corridor 12b"}, 
    "Node 19":{"Node 17":"Corridor 13a", "Node 21":"Corridor 12a", "Node 23":"Corridor 19b","Latin Stairs Ground":"Corridor GSLtn"},
    "Latin Stairs Ground":{"Node 19":"Corridor GSLtn", "Latin Stairs First":"Corridor Latin Ground-First"},
    "Node 20":{"Node 15":"Corridor 15a","Node 20x":"Corridor 15c","Node 20xb":"Corridor 16"},
    "Node 20xa":{"Node 20x":"Corridor 17x", "Node Out1b":"Corridor 20xa-Out1b"},
    "Node 20xb":{"Node 20":"Corridor 16", "English Stairs Ground":"Corridor GSE"},
    "Node 20x":{"Node 20":"Corridor 15c","Node 20xa":"Corridor 17x","Node 17":"Corridor 15b","Node 21":"Corridor 17c"},
    "English Stairs Ground":{"Node 20xb":"Corridor GSE", "English Stairs First":"Corridor English Ground-First"},
    "Node 21":{"Node 20x":"Corridor 17c", "Node 19":"Corridor 12a", "Node 22":"Corridor 17b", },   
    "Node 22":{"Node 21":"Corridor 17b", "Node 23":"Corridor 18a", "Node 25":"Corridor 17a", "Node 27":"Corridor 20"},
    "Node 23":{"Node 22":"Corridor 18a", "Node 24":"Corridor 18b", "Node 26":"Corridor 19a", "Node 19":"Corridor 19b"},
    "Node 24":{"Node 23":"Corridor 18b", "Node 18":"Corridor 11b", "Node 1":"Corridor 11a"},
    "Node 25":{"Node 22":"Corridor 17a", "Node 26":"Corridor 14a", "Node 25x":"Corridor 23b"},
    "Node 25x":{"Node 25":"Corridor 23b","Node 25xa":"Corridor 22", "Staff Dining Stairs Ground":"Corridor GSSD"},
    "Staff Dining Stairs Ground":{"Node 25x":"Corridor GSSD", "Node 25xb":"Corridor 23a", "Staff Dining Stairs First":"Corridor Staff Dining Ground-First"},
    "Node 25xa":{"Node 25x":"Corridor 22"},
    "Node 25xb":{"Staff Dining Stairs Ground":"Corridor 23a"},
    "Node 26":{"Node 25":"Corridor 14a", "Node 23":"Corridor 19a", "Node 1":"Corridor 14b"},
    "Node 26x":{"Node 26":"Corridor 14x", "Node Out2b":"Corridor 26x-Out2b"},
    "Node 27":{"Node 22":"Corridor 20", "Dance Studio Stairs Ground":"Corridor GSDS"}, 
    "Node 27x":{"Dance Studio Stairs Ground":"Corridor 21"}, 
    "Dance Studio Stairs Ground":{"Node 27":"Corridor GSDS", "Node 27x":"Corridor 21","Dance Studio Stairs First":"Corridor Dance Studio Ground-First"},
    "Node 28":{"Node 28xb":"Corridor 24","Node 28xc":"Corridor 25", "Node 28xa":"Corridor 25x"},
    "Node 28xb":{"Node 28":"Corridor 24"},
    "Node 28xa":{"Node 28":"Corridor 25x", "Node Out2a":"Corridor 28xa-Out2a", "Node Out7":"Corridor Out7-28xa"},
    "Node 28xc":{"Node 28":"Corridor 25"},
    "Node Out2a":{"Node 28xa":"Corridor 28xa-Out2a","Node Out2b":"Corridor Out2a-Out2b"},
    "Node Out2b":{"Node Out2a":"Corridor Out2a-Out2b", "Node 26x":"Corridor 26x-Out2b", "Node Out3":"Corridor Out2b-Out3"},
    "Node Out3":{"Node 1x":"Corridor 1x-Out3", "Node Out4":"Corridor Out3-Out4", "Node Out2b":"Corridor Out2b-Out3"},
    "Node Out4":{"Node Out3":"Corridor Out3-Out4", "Node 2x":"Corridor 2x-Out4", "Node Out5":"Corridor Out4-Out5"},
    "Node Out5":{"Node Out5":"Corridor Out4-Out5", "Node 4x":"Corridor 4x-Out5"},
    "Node Out6":{"Node 5xa":"Corridor 5xa-Out6", "Node 10x":"Corridor 10x-Out6"},
    "Node SPb":{"Node 13x":"Corridor 13x-SPb", "Node SPa":"Corridor SPa-SPb", "Node Out1b":"Corridor SPb-Out1b"},
    "Node SPa":{"Node SPb":"Corridor SPa-SPb", "Node SPx":"Sports Pavillion"},
    "Node SPx":{"Node SPa":"Sports Pavillion"},
    "Node Out1b":{"Node SPb":"Corridor SPb-Out1b", "Node M":"Corridor M-Out1b", "Node SHb":"Corridor SHb-Out1b", "Node 20xa":"Corridor 20xa-Out1b"},
    "Node M":{"Node Out1b":"Corridor M-Out1b"},
    "Node SHb":{"Node Out1b":"Corridor SHb-Out1b", "Node SHa":"Corridor SHa-SHb"},
    "Node SHa":{"Node SHb":"Corridor SHa-SHb", "Node SHx":"Sports Hall", "Node Out7":"Corridor SHa-Out7"},
    "Node SHx":{"Node SHa":"Sports Hall"},
    "Node Out7":{"Node SHa":"Corridor SHa-Out7", "Node 28xa":"Corridor Out7-28xa"},

    "Reception Stairs First":{"RS Stairs First":"Corridor 29-StairsA", "Reception Stairs Ground":"Corridor Reception Ground-First"},
    "RS Stairs First":{"Reception Stairs First":"Corridor 29-StairsA","Node 30a":"Corridor 30a-StairsA","Node 30b":"Corridor 30b-StairsA"},  #add second floor connecttion
    "Node 30a":{"RS Stairs First":"Corridor 30a-StairsA"},
    "Node 30b":{"RS Stairs First":"Corridor 30b-StairsA", "Library Stairs First":"Corridor 30b-StairsB","Node 32b":"Corridor 30b-32b"},
    "Library Stairs First":{"Node 30b":"Corridor 30b-StairsB", "Node 31a":"Corridor 31a-StairsB","Library Stairs Ground":"Corridor Library Ground-First"},#add second floor connecttion
    "Node 31a":{"Library Stairs First":"Corridor 31a-StairsB", "Atrium Stairs First":"Corridor 31a-StairsC"},
    "Atrium Stairs First":{"Node 31a":"Corridor 31a-StairsC", "Node 31b":"Corridor 31b-StairsC"},#add second floor connecttion
    "Node 31b":{"Atrium Stairs First":"Corridor 31b-StairsC", "Language Stairs First":"Corridor 31b-StairsD", "History Stairs First":"Corridor 31b-StairsK"},
    "Language Stairs First":{"Node 31b":"Corridor 31b-StairsD", "Node 32b":"Corridor 32b-StairsD", "Language Stairs Ground":"Corridor Language Ground-First"},
    "Node 31c":{"History Stairs First":"Corridor 31c-StairsK", "Chemistry Stairs First":"Corridor 31c-StairsE"},
    "History Stairs First":{"Node 31c":"Corridor 31c-StairsK", "Node 31b":"Corridor 31b-StairsK", "History Stairs Ground":"Corridor History Ground-First"}, 
    "Chemistry Stairs First":{"Node 31c":"Corridor 31c-StairsE", "Node 33b":"Corridor 33b-StairsE", "Chemistry Stairs Ground":"Corridor Chemistry Ground-First"},#add second floor connecttion 
    "Node 32a":{"Node 32b":"Corridor 32a-32b", "Latin Stairs First":"Corridor 32a-Stairs", "Node 33b":"Corridor 32a-33b"},
    "Node 32b":{"Language Stairs First":"Corridor 32b-StairsD", "Node 30b":"Corridor 30b-32b", "Node 32a":"Corridor 32a-32b"},
    "Latin Stairs First":{"Node 32a":"Corridor 32a-Stairs","Latin Stairs Ground":"Corridor Latin Ground-First"},#add second floor connecttion
    "Node 33a":{"Art Stairs First":"Corridor 33a-StairsG", "English Stairs First":"Corridor 33a-StairsH"},
    "Node 33b":{"Chemistry Stairs First":"Corridor 33b-StairsE", "Node 32a":"Corridor 32a-33b", "Bioligy Stairs First":"Corridor 33b-StairsF"},
    "Bioligy Stairs First":{"Node 33b":"Corridor 33b-StairsF", "Art Stairs First":"Corridor StairsF-StairsG", "Bioligy Stairs Ground":"Corridor Bioligy Ground-First"}, #add second floor connecttion
    "Art Stairs First":{"Bioligy Stairs First":"Corridor StairsF-StairsG", "Node 33a":"Corridor 33a-StairsG", "Art Stairs Ground":"Corridor Art Ground-First"}, 
    "English Stairs First":{"Node 33a":"Corridor 33a-StairsH", "English Stairs Ground":"Corridor English Ground-First"}, 
    "Dance Studio Stairs First":{"Node 36a":"Corridor 36a-Stairs", "Dance Studio Stairs Ground":"Corridor Dance Studio Ground-First"}, 
    "Node 36a":{"Dance Studio Stairs First":"Corridor 36a-Stairs", "Node 36b":"Corridor 36a-36b"},
    "Node 36b":{"Node 36a":"Corridor 36a-36b", "Staff Dining Stairs First":"Corridor 36b-Stairs"},
    "Staff Dining Stairs First":{"Node 36b":"Corridor 36b-Stairs", "Node 36c":"Corridor 36c-Stairs", "Staff Dining Stairs Ground":"Corridor Staff Dining Ground-First"}, 
    "Node 36c":{"Staff Dining Stairs First":"Corridor 36c-Stairs"}, #xtx now add coordinates and figure out how to recongise a change in floor
}
    

NodeCoords = {
"Ground Floor":{
    "Node 1":(-2068,-1426),
    "Reception Stairs Ground":(-2068,-1510), 
    "Node 1x":(-2068,-1608),
    "Node 2a":(-2705,-1426),
    "Node 2b":(-2845,-1426),
    "Library Stairs Ground":(-2775,-1426),
    "Node 2x":(-2705,-1629),
    "Node 3a":(-2705,-950),
    "Node 3b":(-2705,-901),
    "Language Stairs Ground":(-2705,-862),
    "Node 4":(-2845,-901),
    "Node 4x":(-3034,-901),
    "Node 5":(-2845,-789),
    "History Stairs Ground":(-2845,-705),
    "Node 5xa":(-3034,-705),
    "Node 5xb":(-2908,-705),
    "Node 6":(-2705,-789),
    "Node 7":(-2509,-789),
    "Node 8":(-2908,-579),
    "Node 9":(-2705,-579),
    "Node 10":(-2509,-579),
    "Chemistry Stairs Ground":(-2579,-579),
    "Node 10x":(-2509,-404),
    "Node 11":(-2313,-579),
    "Node 12":(-2068,-579),
    "Node 13":(-1893,-579),
    "Bioligy Stairs Ground":(-1956,-579),
    "Node 13x":(-1893,-404),
    "Node 14":(-1739,-579),
    "Node 15":(-1382,-579),
    "Art Stairs Ground":(-1522,-579),
    "Node 16":(-2068,-789),
    "Node 17":(-1739,-719),
    "Node 18":(-2068,-950),
    "Node 19":(-1739,-950),
    "Latin Stairs Ground":(-1886,-950),
    "Node 20":(-1382,-670),
    "Node 20xa":(-1235,-719),
    "Node 20xb":(-976,-670),
    "Node 20x":(-1382,-719), 
    "English Stairs Ground":(-927,-670),
    "Node 21":(-1382,-950),
    "Dance Studio Stairs Ground":(-906,-1244),
    "Node 22":(-1382,-1181),
    "Node 23":(-1739,-1181),
    "Node 24":(-2068,-1181),
    "Node 25":(-1382,-1426),
    "Staff Dining Stairs Ground":(-1382,-1580),
    "Node 25x":(-1382,-1503),
    "Node 25xa":(-976,-1503),
    "Node 25xb":(-1382,-1797),
    "Node 26":(-1739,-1426),
    "Node 26x":(-1739,-1580),
    "Node 27":(-906,-1181),
    "Node 27x":(-906,-1433),
    "Node 28":(-1578,-2098),
    "Node 28xb":(-878,-2098),
    "Node 28xa":(-1578,-1965),
    "Node 28xc":(-1578,-2308),
    "Node Out2a":(-1739,-1965),
    "Node Out2b":(-1739,-1755),
    "Node Out3":(-2068,-1755),
    "Node Out4":(-2705,-1755),
    "Node Out5":(-3034,-1755),
    "Node Out6":(-3034,-404),
    "Node SPb":(-738,-404),
    "Node SPa":(-521,-404),
    "Node SPx":(-521,-152),
    "Node Out1b":(-738,-719),
    "Node M":(-535,-719),
    "Node SHb":(-738,-1048),
    "Node SHa":(-598,-1048),
    "Node SHx":(-437,-1048),
    "Node Out7":(-598,-1965),
},
"First Floor":{
    "Reception Stairs First":(-2054,-1510),
    "RS Stairs First":(-2054,-1412),
    "Node 30a":(-1928,-1412),
    "Node 30b":(-2691,-1412),
    "Library Stairs First":(-2754,-1412),
    "Node 31a":(-2922,-1412),
    "Atrium Stairs First":(-2922,-1251),
    "Node 31b":(-2922,-922),
    "Language Stairs First":(-2754,-922),
    "Node 31c":(-2922,-558),
    "History Stairs First":(-2922,-642),
    "Chemistry Stairs First":(-2523,-558), 
    "Node 32a":(-2068,-922),
    "Node 32b":(-2691,-922),
    "Latin Stairs First":(-1837,-922),
    "Node 33a":(-941,-558),
    "Node 33b":(-2068,-558),
    "Bioligy Stairs First":(-1935,-558),
    "Art Stairs First":(-1501,-558),
    "English Stairs First":(-941,-649),
    "Dance Studio Stairs First":(-906,-1230),
    "Node 36a":(-906,-1167),
    "Node 36b":(-1396,-1167),
    "Staff Dining Stairs First":(-1396,-1552),
    "Node 36c":(-1396,-1881),
},
"Second Floor":{},
    }
